name: beta-deployments
on:
  push:
    branches:
      - main
jobs:
  build_android:
    name: Build Flutter (Android)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - name: Checkout LFS objects
        run: git lfs checkout
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - run: echo "y" | sudo ${ANDROID_HOME}/tools/bin/sdkmanager --install "ndk;20.0.5594570"
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - uses: RollyPeres/base64-to-path@v1
        with:
          filePath: ${{ github.workspace }}/android/key.jks
          encodedString: ${{ secrets.ANDROID_KEY_JKS }}
      - run: flutter pub get
      - run: flutter build apk --release
        env:
          ANDROID_STORE_PASSWORD: ${{ secrets.ANDROID_STORE_PASSWORD }}
          ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
          ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
      - name: Upload artifact
        uses: actions/upload-artifact@master
        with:
          name: android-build
          path: build/app/outputs/flutter-apk
  beta_android:
    name: Upload Android Beta to Firebase App Distribution
    needs: [build_android]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: android-build
      - name: Upload Artifact
        uses: wzieba/Firebase-Distribution-Github-Action@v1.2.1
        with:
          appId: ${{ secrets.FIREBASE_ANDROID_APPID }}
          token: ${{ secrets.FIREBASE_TOKEN }}
          groups: testers
          file: app-release.apk
