# Courtesy of Rody Davis @rodydavis
# https://gist.github.com/rodydavis/bde9a9a8c2fcdcf3474c0f50248f2e3a

name: build
on:
  pull_request:
    branches:
      - main
jobs:
  # build_ios:
  #   name: Build Flutter (iOS)
  #   runs-on: macOS-latest
  #   steps:
  #     - uses: actions/checkout@v1
  #     - uses: actions/setup-java@v1
  #       with:
  #         java-version: "12.x"
  #     - uses: subosito/flutter-action@v1
  #       with:
  #         channel: "beta"
  #     - uses: apple-actions/import-codesign-certs@v1
  #       with:
  #         p12-file-base64: ${{ secrets.IOS_CERTIFICATES_P12 }}
  #         p12-password: ${{ secrets.IOS_CERTIFICATES_P12_PASSWORD }}
  #     - run: flutter pub get
  #     - run: flutter clean
  #     - run: flutter build ios --release --no-codesign
  #       uses: apple-actions/import-codesign-certs@v1
  #       with:
  #         p12-file-base64: ${{ secrets.IOS_CERTIFICATES_P12 }}
  #         p12-password: ${{ secrets.IOS_CERTIFICATES_P12_PASSWORD }}
  #     - run: xcodebuild -workspace ios/Runner.xcworkspace -scheme Runner -sdk iphoneos -configuration Release archive -archivePath build/Runner.xcarchive OTHER_CODE_SIGN_FLAGS='--keychain /Users/runner/Library/Keychains/signing_temp.keychain-db'
  #     - run: xcodebuild -exportArchive -archivePath build/Runner.xcarchive -exportOptionsPlist ios/ExportOptions.plist -exportPath build/ios/iphoneos/Runner.ipa OTHER_CODE_SIGN_FLAGS='--keychain /Users/runner/Library/Keychains/signing_temp.keychain-db'
  build_android:
    name: Build Flutter (Android)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - run: echo "y" | sudo ${ANDROID_HOME}/tools/bin/sdkmanager --install "ndk;20.0.5594570"
      - uses: subosito/flutter-action@v1
        with:
          channel: "beta"
      - uses: RollyPeres/base64-to-path@v1
        with:
          filePath: ${{ github.workspace }}/android/key.jks
          encodedString: ${{ secrets.ANDROID_KEY_JKS }}
      - run: flutter pub get
      - run: flutter build apk --release
        env:
          ANDROID_STORE_PASSWORD: ${{ secrets.ANDROID_STORE_PASSWORD }}
          ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
          ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
